package com.ruleengine.jsp.com.rules.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DTO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DTO() {
    }




}