package com.ruleengine.jsp.com.rules.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class newDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer id;
	private java.lang.Integer age;

	public newDTO() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public newDTO(java.lang.Integer id, java.lang.Integer age) {
		this.id = id;
		this.age = age;
	}

}